version: '3'

services:
  nginx:
    container_name: ${DOCKER_NGINX_CONTAINER_NAME}
    image: shangxian/nginx:alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './inc:/etc/nginx/inc'
      - './html:/etc/nginx/html'
      - "${DOCKER_NGINX_VHOST_DIR}:/etc/nginx/vhost"
      - "${DOCKER_NGINX_CA_DIR}:/etc/nginx/ca"
      - "${WWWROOT_DIR}:/usr/share/nginx/html"
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - DOCKER_NGINX_VHOST_DIR=/etc/nginx/vhost
      - DOCKER_NGINX_CA_DIR=/etc/nginx/ca
      - WWWROOT_DIR=/usr/share/nginx/html

networks:
  default:
    external:
      name: "${DOCKER_PRIVATE_NETWORK_NAME}"